### ISSUE TITLE
Walkable Height creates an issue for my geo engine (help needed)

### ISSUE THREAD

**Issue by Bru7aLMike** [madyanov/l2mapconv-public#13]
It produces geodata cells in the inside of meshes and over buried meshes.
In the case of buried meshes, it takes the terrain as a factor in the calculations of start-end Z coordinates. However, I would like to make it so that it disregards the terrain when the mesh has Z value lower than the Z value of the Terrain in the same cell, and instead only uses Z values of other static meshes. 
Also, is it possible to only create geodata cells for static meshes on the outside of the mesh, as opposed to within the mesh when the mesh itself is comprised of multiple layers (screenshot 3, 4, and 5 show that it creates geo within the mesh itself, in between its inner layers)?

Is there a way for me to manually edit a file or two, figuratively speaking, to make it so that it does not create 
1- Walkable Height geodata points between the outer layer of the mesh and the terrain when the specific point at which it wants to create the geo cell on the static mesh has Z value lower than the Z value of the terrain
2- geodata points within the mesh itself?

And if so, in which file/s should I poke around, and what should I be looking for?

Geodata file from another source 1:
![image](https://user-images.githubusercontent.com/72753019/101274994-10757300-37ab-11eb-9bb7-fef45e11aecd.png)

Produced by l2mapconv 1:
![image](https://user-images.githubusercontent.com/72753019/101275004-1ff4bc00-37ab-11eb-9cfa-5b658b145bf9.png)

The static mesh itself:
![image](https://user-images.githubusercontent.com/72753019/101275200-76162f00-37ac-11eb-90c8-da07800d2f8d.png)

Geodata file from another source 2:
![image](https://user-images.githubusercontent.com/72753019/101275033-4286d500-37ab-11eb-8ffa-0b00f9b43443.png)

Produced by l2mapconv 2:
![image](https://user-images.githubusercontent.com/72753019/101275039-516d8780-37ab-11eb-9fdf-b7d4d76e7c27.png)

**Comment by madyanov** [comment]
> However, I would like to make it so that it disregards the terrain when the mesh has Z value lower than the Z value of the Terrain in the same cell, and instead only uses Z values of other static meshes.

But what about catacombs, necropolis, stadiums and many other locations below terrain?

**Comment by Bru7aLMike** [comment]
I totally agree that a better engine would've handled the issue with ease. However, the one I'm using handles layers very poorly. In fact, it has <20 lines of code for handling layers. I'm still trying to figure out how to solve the issue within the engine itself, but in the meantime, I was wondering if making changes to the converter wouldn't be the better/easier/faster solution for the time being. I've noticed that the majority of the biggest servers from the past, to the sources of which I could lay my hands on, were using pretty much the same geo engine with a few small changes here and there. However, reproducing the code in the source I have is not an easy task, especially for someone who is not a developer, such as myself.

**Comment by madyanov** [comment]
You can look at this geoengines with diagonal path smoothing: https://github.com/search?l=Java+Properties&q=PathFindDiagonal&type=Code
