### ISSUE TITLE
How do I fix this (possibly broken export)

### ISSUE THREAD

**Issue by Bru7aLMike** [madyanov/l2mapconv-public#14]
As you can see from the images below, the preview of the exported geodata is different from the preview of the imported geodata, while the imported file is the one that I just exported, just copied from the output folder to the geodata folder.

Expected result (from the preview window):

![image](https://user-images.githubusercontent.com/72753019/103768460-35b80400-502b-11eb-9d75-8f3f28efc43d.png)

The real result when you export and then reload to check the end result:

![image](https://user-images.githubusercontent.com/72753019/103768543-5d0ed100-502b-11eb-8088-84f99a389f68.png)

**Comment by madyanov** [comment]
Which map and client?

**Comment by Bru7aLMike** [comment]
I assume it happens on every map that has underground layers. This one, in particular, is Classic 25_17 (devastated castle).

**Comment by madyanov** [comment]
Can't reproduce it on HF client, but found some artifacts:

![Desktop Screenshot 2021 01 07 - 15 09 43 92](https://user-images.githubusercontent.com/8654433/103891300-a8dc7b80-50fa-11eb-9d2e-9edc0a16142a.png)

Looks like still broken export.

**Comment by madyanov** [comment]
Issue with artifacts fixed in v1.0.1 (https://github.com/madyanov/l2mapconv-public/releases/tag/v1.0.1)
