### ISSUE TITLE
Rendering (Shader) error

### ISSUE THREAD

**Issue by Bru7aLMike** [madyanov/l2mapconv-public#9]
I've followed the installation process, cloned the entire repository, installed the required programmes, added the ninja file where required, built the project, and then I went on to build the geodata files. However, when I added them to my server, they were all empty (my character was phasing through the walls and all that, as if the geodata was non-existent, despite the fact that the gameserver CMD window shows that certain amount of the geodata files were loaded. 159 geodata files loaded out of 238 total) 

And when I tried the preview option, I got the following error with the preview window showing nothing but black screen. Any ideas as to what I'm doing wrong?

![image](https://user-images.githubusercontent.com/72753019/100489963-63528900-3120-11eb-85f8-cdeb5ffafd9f.png)

**Comment by madyanov** [comment]
> when I added them to my server, they were all empty

That means you built not all geodata.

> Any ideas as to what I'm doing wrong?

Yeah. Should be fixed in this branch https://github.com/madyanov/l2mapconv-public/tree/geodata-builder-rc5. Check it out.

**Comment by Bru7aLMike** [comment]
Thanks, it does work, indeed!
